from typing import Any

from pydantic import BaseModel, Field


class Citation(BaseModel):
    """Provenance and context metadata for a retrieved chunk supporting an answer."""

    chunk_id: str = Field(description="Unique identifier of the referenced chunk")
    doc_id: str = Field(description="Parent document identifier")
    source: str = Field(description="Original document source path or filename")
    file_type: str = Field(description="Document format/extension (txt, pdf, md)")
    chunk_index: int = Field(description="0-indexed position of the chunk in the document")
    content: str = Field(description="Exact text content of the chunk")
    similarity: float = Field(description="Cosine similarity score against user query")
    document_type: str | None = Field(default=None, description="Semantic document type")
    department: str | None = Field(default=None, description="Originating department")
    date: str | None = Field(default=None, description="Document date")
    author: str | None = Field(default=None, description="Document author")
    tags: list[str] = Field(default_factory=list, description="Document tags")
    initial_rank: int | None = Field(
        default=None, description="Ordinal rank before reranking"
    )
    rerank_score: float | None = Field(
        default=None, description="Relevance score assigned by reranker"
    )
    metadata: dict[str, Any] = Field(
        default_factory=dict,
        description="Preserved document and chunk metadata tags",
    )


class RAGResponse(BaseModel):
    """Grounded answer generated by RAG with citation metadata and provenance."""

    question: str = Field(description="User question asked")
    answer: str = Field(description="Grounded response generated by the model")
    citations: list[Citation] = Field(
        default_factory=list,
        description="List of document chunks used as ground truth for the answer",
    )
    retrieved_chunks_count: int = Field(
        description="Number of chunks retrieved from vector storage"
    )
    model: str = Field(description="LLM model identifier used for generation")
    provider: str = Field(description="LLM provider name (mock, openai)")
    prompt_tokens: int | None = Field(default=None, description="Prompt token count")
    completion_tokens: int | None = Field(default=None, description="Completion token count")
    total_tokens: int | None = Field(default=None, description="Total tokens consumed")
    final_query: str | None = Field(
        default=None, description="Final rewritten query used for retrieval"
    )
    strategy: str = Field(
        default="normal", description="Retrieval strategy: 'normal' or 'hyde'"
    )
    hypothetical_document: str | None = Field(
        default=None, description="Hypothetical document passage synthesized by HyDE"
    )
    metadata: dict[str, Any] = Field(
        default_factory=dict, description="Execution telemetry and rewrite history"
    )
