from enum import StrEnum
from typing import Any

from pydantic import BaseModel, Field


class HealthResponse(BaseModel):
    """Health check response schema."""

    status: str = Field(default="ok", description="Service health status")
    version: str = Field(description="Application version")
    environment: str = Field(description="Deployment environment")


class AppInfoResponse(BaseModel):
    """Application metadata response schema."""

    app_name: str = Field(description="Application name")
    version: str = Field(description="Application version")
    environment: str = Field(description="Current running environment")
    api_version: str = Field(description="API version prefix")


class ErrorDetail(BaseModel):
    """Structured error payload details."""

    code: str = Field(description="Machine-readable error code")
    message: str = Field(description="Human-readable error description")
    details: Any = Field(default=None, description="Optional extra error details")
    request_id: str | None = Field(default=None, description="Request correlation ID")


class ErrorResponse(BaseModel):
    """Standardized API error response format."""

    error: ErrorDetail


class ChatRequest(BaseModel):
    """Chat completion request payload."""

    message: str = Field(
        min_length=1,
        max_length=16000,
        description="Prompt message to send to the LLM",
        examples=["Explain semiconductor manufacturing in simple terms."],
    )
    system_prompt: str | None = Field(
        default=None,
        max_length=4000,
        description="Optional system prompt instructions for the LLM",
    )
    temperature: float | None = Field(
        default=None,
        ge=0.0,
        le=2.0,
        description="Sampling temperature",
    )
    max_tokens: int | None = Field(
        default=None,
        gt=0,
        le=32000,
        description="Maximum tokens to generate",
    )


class ChatResponse(BaseModel):
    """Chat completion response payload."""

    answer: str = Field(description="The response text generated by the LLM")
    model: str | None = Field(default=None, description="The model used for generation")
    provider: str | None = Field(default=None, description="The LLM provider used")


class TaskStatus(StrEnum):
    """Execution status of an Agent task."""

    PENDING = "pending"
    PLANNING = "planning"
    EXECUTING = "executing"
    COMPLETED = "completed"
    FAILED = "failed"


class TaskRequest(BaseModel):
    """Agent task execution request payload."""

    task: str = Field(
        min_length=1,
        max_length=16000,
        description="The task or problem to be executed by the agent",
        examples=["Explain how semiconductor manufacturing works."],
    )
    system_instructions: str | None = Field(
        default=None,
        max_length=4000,
        description="Optional high-level instructions or constraints for the agent",
    )


class ExecutionMetadata(BaseModel):
    """Metadata regarding task execution, telemetry, and version provenance."""

    model: str = Field(description="The LLM model used for execution")
    provider: str = Field(description="The LLM provider adapter used")
    duration_ms: float = Field(description="Total execution latency in milliseconds")
    prompt_tokens: int = Field(default=0, description="Cumulative tokens in prompts")
    completion_tokens: int = Field(default=0, description="Cumulative tokens in completions")
    total_tokens: int = Field(default=0, description="Total tokens consumed across all steps")
    tools_used: list[str] = Field(
        default_factory=list,
        description="List of tools invoked during execution",
    )
    trace: list[str] = Field(default_factory=list, description="Ordered execution step trace")

    # Milestone 50: Configuration & Prompt Version Provenance
    config_version: str = Field(default="1.0.0", description="Active Agent system configuration version")
    composite_config_hash: str = Field(
        default="",
        description="Deterministic SHA-256 fingerprint of the complete configuration snapshot",
    )
    prompt_versions: dict[str, str] = Field(
        default_factory=dict,
        description="Active version identifiers for each prompt component",
    )
    model_config_version: str = Field(default="1.0.0", description="Active model configuration version")
    retrieval_config_version: str = Field(default="1.0.0", description="Active retrieval configuration version")
    routing_config_version: str = Field(default="1.0.0", description="Active routing configuration version")


class TaskResponse(BaseModel):
    """Structured response returned upon agent task completion."""

    task_id: str = Field(description="Unique task execution identifier")
    task: str = Field(description="The original task submitted by the user")
    status: TaskStatus = Field(description="Final execution status")
    plan: list[str] = Field(
        default_factory=list,
        description="Structured plan steps formulated by the agent",
    )
    answer: str | None = Field(default=None, description="Generated answer or solution")
    error: str | None = Field(default=None, description="Error message if execution failed")
    metadata: ExecutionMetadata = Field(description="Execution metadata and telemetry")


class TextIngestRequest(BaseModel):
    """Request payload for direct raw text ingestion."""

    content: str = Field(
        min_length=1,
        max_length=500000,
        description="Raw document text content to ingest",
    )
    source_name: str = Field(
        default="direct_input.txt",
        description="Logical filename or identifier for the document",
    )
    document_type: str | None = Field(
        default=None,
        description="Semantic document type classification",
    )
    department: str | None = Field(default=None, description="Originating department")
    date: str | None = Field(default=None, description="Document date string")
    author: str | None = Field(default=None, description="Document author")
    tags: list[str] = Field(default_factory=list, description="Categorization tags")
    custom_metadata: dict[str, Any] = Field(
        default_factory=dict,
        description="Optional custom tags or metadata",
    )


class DocumentIngestResponse(BaseModel):
    """Response returned upon document ingestion."""

    doc_id: str = Field(description="Unique document identifier")
    status: str = Field(description="Ingestion outcome ('ingested', 'skipped_duplicate', 'failed')")
    source: str = Field(description="Source document name")
    checksum: str = Field(description="SHA-256 hash of document content")
    message: str = Field(description="Informational status message")
    character_count: int = Field(default=0, description="Total characters extracted")
    word_count: int = Field(default=0, description="Total words extracted")
    page_count: int | None = Field(default=None, description="Total pages if paginated")


class DocumentListResponse(BaseModel):
    """Response containing list of all ingested document metadata."""

    total: int = Field(description="Total number of documents stored")
    documents: list[dict[str, Any]] = Field(
        default_factory=list,
        description="List of document metadata objects",
    )


class ChunkDocumentRequest(BaseModel):
    """Optional parameters for chunking an ingested document."""

    chunk_size: int | None = Field(default=None, gt=0, description="Override target chunk size")
    chunk_overlap: int | None = Field(default=None, ge=0, description="Override chunk overlap")


class ChunkTextRequest(BaseModel):
    """Request payload for chunking raw text directly."""

    text: str = Field(min_length=1, description="Raw text to partition into chunks")
    source_name: str = Field(
        default="direct_input.txt",
        description="Source document identifier",
    )
    chunk_size: int | None = Field(
        default=None,
        gt=0,
        description="Target chunk size in characters",
    )
    chunk_overlap: int | None = Field(
        default=None,
        ge=0,
        description="Chunk overlap in characters",
    )
    custom_metadata: dict[str, Any] = Field(
        default_factory=dict,
        description="Custom metadata tags",
    )


class ChunkResponse(BaseModel):
    """Response containing generated document chunks."""

    doc_id: str = Field(description="Parent document identifier")
    total_chunks: int = Field(description="Number of chunks generated")
    chunks: list[dict[str, Any]] = Field(
        description="List of serialized DocumentChunk objects",
    )
    preview_diagram: str | None = Field(
        default=None,
        description="Visual document -> chunks ASCII diagram",
    )


class EmbeddingGenerateRequest(BaseModel):
    """Request payload to generate embeddings for a batch of strings."""

    texts: list[str] = Field(
        min_length=1,
        description="List of text strings to embed",
    )


class EmbeddingGenerateResponse(BaseModel):
    """Response containing generated dense vector embeddings."""

    model: str = Field(description="Embedding model name")
    dimensions: int = Field(description="Embedding vector dimensionality")
    total_embeddings: int = Field(description="Total count of embeddings returned")
    embeddings: list[list[float]] = Field(description="List of numeric vector arrays")
    total_tokens: int = Field(default=0, description="Tokens consumed")
    duration_ms: float = Field(default=0.0, description="Latency in milliseconds")


class EmbedDocumentResponse(BaseModel):
    """Response returned when an ingested document is chunked and embedded."""

    doc_id: str = Field(description="Document ID")
    total_chunks: int = Field(description="Number of embedded chunks produced")
    dimensions: int = Field(description="Vector dimensions of the embeddings")
    status: str = Field(default="indexed", description="Storage and indexing status")
    chunks: list[dict[str, Any]] = Field(
        default_factory=list,
        description="Serialized EmbeddedChunk objects with vector data",
    )


class SimilarityRequest(BaseModel):
    """Request to calculate cosine similarity between two text strings."""

    text_a: str = Field(min_length=1, description="First text string")
    text_b: str = Field(min_length=1, description="Second text string")


class SimilarityResponse(BaseModel):
    """Response containing cosine similarity score."""

    text_a: str = Field(description="First text string")
    text_b: str = Field(description="Second text string")
    cosine_similarity: float = Field(description="Cosine similarity score [-1.0 to 1.0]")


class VectorSearchRequest(BaseModel):
    """Request payload for semantic vector similarity search with optional metadata filtering."""

    query: str = Field(min_length=1, description="Natural language search query")
    top_k: int = Field(default=5, gt=0, le=50, description="Max number of results to return")
    min_similarity: float = Field(
        default=0.0,
        ge=-1.0,
        le=1.0,
        description="Minimum cosine similarity threshold",
    )
    filters: dict[str, Any] | None = Field(
        default=None,
        description="Optional metadata filters (e.g. {'document_type': 'quality_report'})",
    )
    mode: str | None = Field(
        default=None,
        description="Retrieval mode: 'hybrid', 'semantic', 'keyword' (defaults to config)",
    )
    alpha: float | None = Field(
        default=None,
        ge=0.0,
        le=1.0,
        description="Optional dense weight for weighted hybrid fusion [0.0 - 1.0]",
    )


class VectorSearchResultItem(BaseModel):
    """A single matched chunk item from a vector similarity search."""

    chunk_id: str = Field(description="Unique chunk identifier")
    doc_id: str = Field(description="Parent document identifier")
    content: str = Field(description="Text content of the matching chunk")
    similarity: float = Field(description="Cosine similarity score [0.0 to 1.0]")
    document_type: str | None = Field(default=None, description="Semantic document type")
    department: str | None = Field(default=None, description="Originating department")
    date: str | None = Field(default=None, description="Document date")
    author: str | None = Field(default=None, description="Document author")
    tags: list[str] = Field(default_factory=list, description="Categorization tags")
    metadata: dict[str, Any] = Field(description="Preserved chunk and document metadata")


class VectorSearchResponse(BaseModel):
    """Response containing matched vector search results."""

    query: str = Field(description="Search query string")
    mode: str = Field(default="hybrid", description="Retrieval mode executed")
    total_results: int = Field(description="Total count of results matching criteria")
    results: list[VectorSearchResultItem] = Field(description="Ranked list of matching chunks")


class SyncKnowledgeBaseRequest(BaseModel):
    """Request payload for synchronizing the knowledge base directory."""

    kb_dir: str | None = Field(
        default=None,
        description="Path to knowledge base directory (defaults to configured settings)",
    )
    chunk_size: int | None = Field(
        default=None,
        gt=0,
        description="Optional chunk size override",
    )
    chunk_overlap: int | None = Field(
        default=None,
        ge=0,
        description="Optional chunk overlap override",
    )


class SyncKnowledgeBaseResponse(BaseModel):
    """Response summarizing knowledge base directory synchronization."""

    kb_dir: str = Field(description="Directory path that was synced")
    status: str = Field(description="Sync status (success / error)")
    total_files: int = Field(description="Total files processed in directory")
    ingested: int = Field(description="New files ingested")
    skipped: int = Field(description="Duplicate files skipped")
    indexed_documents: int = Field(description="Total documents indexed into vector DB")
    total_indexed_chunks: int = Field(description="Total chunks embedded and indexed")


class RAGQueryRequest(BaseModel):
    """Request payload for RAG question answering with optional metadata filtering."""

    question: str = Field(min_length=1, description="Natural language question to answer")
    top_k: int = Field(
        default=5,
        gt=0,
        le=50,
        description="Number of top relevant chunks to retrieve for grounding",
    )
    min_similarity: float = Field(
        default=0.0,
        ge=-1.0,
        le=1.0,
        description="Minimum cosine similarity threshold for retrieved context",
    )
    system_prompt: str | None = Field(
        default=None,
        description="Optional system prompt overriding default grounding instructions",
    )
    filters: dict[str, Any] | None = Field(
        default=None,
        description="Optional metadata filters (e.g. {'document_type': 'quality_report'})",
    )
    mode: str | None = Field(
        default=None,
        description="Retrieval mode: 'hybrid', 'semantic', 'keyword' (defaults to config)",
    )
    alpha: float | None = Field(
        default=None,
        ge=0.0,
        le=1.0,
        description="Optional dense weight for weighted hybrid fusion [0.0 - 1.0]",
    )
    rerank: bool | None = Field(
        default=None,
        description="Enable post-retrieval cross-encoder / reranking stage",
    )
    top_n: int | None = Field(
        default=None,
        gt=0,
        le=100,
        description="Number of initial candidate chunks to retrieve before reranking (Top N)",
    )
    enable_rewriting: bool | None = Field(
        default=None,
        description="Enable iterative query rewriting and retrieval evaluation loop",
    )
    max_attempts: int | None = Field(
        default=None,
        ge=1,
        le=10,
        description="Maximum number of query rewrite and retrieval iterations",
    )
    strategy: str | None = Field(
        default=None,
        description="Retrieval strategy: 'normal' (standard hybrid/vector) or 'hyde'",
    )
    hyde: bool | None = Field(
        default=None,
        description="Enable HyDE (Hypothetical Document Embeddings) retrieval",
    )


class CitationItem(BaseModel):
    """Citation provenance item returned in RAG query response."""

    chunk_id: str = Field(description="Unique chunk identifier")
    doc_id: str = Field(description="Parent document identifier")
    source: str = Field(description="Original document source path or filename")
    file_type: str = Field(description="Document format (txt, pdf, md)")
    chunk_index: int = Field(description="Ordinal position of chunk in parent document")
    content: str = Field(description="Exact text content of the retrieved chunk")
    similarity: float = Field(description="Cosine similarity or rerank score against question")
    document_type: str | None = Field(default=None, description="Semantic document type")
    department: str | None = Field(default=None, description="Originating department")
    date: str | None = Field(default=None, description="Document date")
    author: str | None = Field(default=None, description="Document author")
    tags: list[str] = Field(default_factory=list, description="Document tags")
    initial_rank: int | None = Field(
        default=None, description="Initial rank position before reranking"
    )
    rerank_score: float | None = Field(
        default=None, description="Score assigned by reranker stage"
    )
    metadata: dict[str, Any] = Field(default_factory=dict, description="Metadata tags")


# Backward compatibility alias
Citation = CitationItem


class RerankMeasurementItem(BaseModel):
    """Telemetry item recording rank position shift before and after reranking."""

    chunk_id: str = Field(description="Unique chunk identifier")
    source: str = Field(description="Document source name")
    initial_rank: int = Field(description="Rank position before reranking")
    reranked_rank: int = Field(description="Rank position after reranking")
    initial_score: float = Field(description="Score before reranking")
    rerank_score: float = Field(description="Score assigned by reranker")
    rank_delta: int = Field(description="Position change: positive = moved up")


class QueryRewriteAttemptItem(BaseModel):
    """Telemetry item recording one iteration of query rewriting and evaluation."""

    attempt: int = Field(description="Iteration attempt number (1-based)")
    query: str = Field(description="Query string executed in this attempt")
    retrieved_count: int = Field(description="Number of chunks retrieved")
    top_score: float = Field(description="Top score in this iteration")
    average_score: float = Field(description="Average score across retrieved chunks")
    is_sufficient: bool = Field(description="Whether retrieval was evaluated as sufficient")
    reasons: list[str] = Field(
        default_factory=list, description="Evaluation deficiency reasons"
    )
    feedback: str | None = Field(default=None, description="Prescriptive evaluator feedback")


class RAGQueryResponse(BaseModel):
    """Response payload containing grounded answer and verified citation metadata."""

    question: str = Field(description="Question asked by the user")
    final_query: str | None = Field(
        default=None,
        description="Final rewritten query used for retrieval (if rewritten)",
    )
    strategy: str = Field(
        default="normal",
        description="Retrieval strategy used: 'normal' or 'hyde'",
    )
    hypothetical_document: str | None = Field(
        default=None,
        description="Synthetic document passage generated by HyDE (if HyDE strategy enabled)",
    )
    answer: str = Field(description="Grounded answer synthesized by LLM")
    citations: list[CitationItem] = Field(
        default_factory=list,
        description="List of cited chunks used as ground truth",
    )
    retrieved_chunks_count: int = Field(description="Number of chunks retrieved from storage")
    retrieval_mode: str = Field(default="hybrid", description="Retrieval strategy utilized")
    reranked: bool = Field(default=False, description="Whether reranking was executed")
    rerank_metrics: list[RerankMeasurementItem] | None = Field(
        default=None,
        description="Before/after rank transition telemetry when reranking is enabled",
    )
    rewrite_history: list[QueryRewriteAttemptItem] | None = Field(
        default=None,
        description="History of all query rewrite iterations and evaluator feedback",
    )
    model: str = Field(description="LLM model identifier")
    provider: str = Field(description="LLM provider name")
    metadata: dict[str, Any] = Field(
        default_factory=dict,
        description="Execution statistics and token usage metadata",
    )


class AnalyzeQueryRequest(BaseModel):
    """Request payload for semantic query decomposition and intent analysis."""

    query: str = Field(
        min_length=1,
        max_length=2000,
        description="User query string to be analyzed",
        examples=[
            (
                "What were the main reasons for Boeing's production delays "
                "and how did those compare with Airbus?"
            )
        ],
    )


class ExtractedEntityItem(BaseModel):
    """Entity extracted from query text."""

    text: str = Field(description="Text of the entity extracted from query")
    label: str = Field(description="Entity label classification")
    category: str | None = Field(default=None, description="Ontological category")


class AnalyzeQueryResponse(BaseModel):
    """Structured understanding and decomposition of the user query."""

    original_query: str = Field(description="Original query analyzed")
    intent: str = Field(description="Identified semantic intent category")
    entities: list[ExtractedEntityItem] = Field(
        default_factory=list,
        description="Named entities, organizations, products, and technical terms",
    )
    subquestions: list[str] = Field(
        default_factory=list,
        description="Atomic subquestions broken down from the query",
    )
    required_information_types: list[str] = Field(
        default_factory=list,
        description="Categories of information needed to answer the query",
    )
    potential_source_types: list[str] = Field(
        default_factory=list,
        description="Candidate document source types likely containing answers",
    )
    is_ambiguous: bool = Field(description="Whether the query is underspecified or ambiguous")
    clarification_needed: str | None = Field(
        default=None,
        description="Recommended clarification request if ambiguous",
    )
    temporal_scope: str | None = Field(
        default=None,
        description="Identified date or timeframe scope",
    )
    confidence_score: float = Field(description="Confidence score [0.0 - 1.0]")


class RouteQueryRequest(BaseModel):
    """Request to determine optimal knowledge sources for a user query."""

    query: str = Field(
        min_length=1,
        description="Question or search query to evaluate for multi-source routing",
        examples=["Compare our internal sales numbers with public market information."],
    )


class RouteQueryResponse(BaseModel):
    """Structured routing decision returned by the retrieval router."""

    query: str = Field(description="Query evaluated")
    intent: str = Field(description="Analyzed query intent category")
    selected_sources: list[str] = Field(
        description="Target source destinations (e.g. internal_documents, external_web)"
    )
    reason: str = Field(description="Justification and rationale for the routing decision")
    confidence: float = Field(description="Confidence score between 0.0 and 1.0")
    entities_detected: list[str] = Field(
        default_factory=list,
        description="Named entities identified during query routing analysis",
    )


class EvidenceEvaluationItem(BaseModel):
    """Structured evaluation of retrieved evidence sufficiency."""

    status: str = Field(description="Sufficiency status: 'sufficient' or 'needs_more_retrieval'")
    is_sufficient: bool = Field(description="Whether evidence is sufficient for generation")
    relevance_score: float = Field(description="Mean relevance/similarity score [0.0 - 1.0]")
    coverage_score: float = Field(description="Entity/concept coverage score [0.0 - 1.0]")
    source_diversity_score: float = Field(description="Source representation score [0.0 - 1.0]")
    evidence_quantity: int = Field(description="Number of evidence passages retrieved")
    confidence: float = Field(description="Overall confidence score [0.0 - 1.0]")
    reason: str = Field(description="Justification for evaluation outcome")
    missing_entities: list[str] = Field(default_factory=list, description="Uncovered entities")
    missing_sources: list[str] = Field(default_factory=list, description="Unqueried sources")


class AdaptiveRetrievalRequest(BaseModel):
    """Request to adaptively retrieve, evaluate evidence, and conditionally generate answers."""

    query: str = Field(
        min_length=1,
        description="User question to evaluate adaptively",
        examples=["What does our internal quality policy say about flutter dampers?"],
    )
    max_rounds: int = Field(
        default=2,
        ge=1,
        le=5,
        description="Maximum allowed retrieval rounds to prevent infinite loops",
    )
    generate_answer: bool = Field(
        default=True,
        description="Whether to generate LLM answer if evidence is sufficient",
    )


class AdaptiveRetrievalResponse(BaseModel):
    """Response returned by adaptive retrieval pipeline."""

    query: str = Field(description="Question processed")
    status: str = Field(description="Final sufficiency status (sufficient / needs_more_retrieval)")
    rounds_executed: int = Field(description="Total rounds executed")
    max_rounds: int = Field(description="Maximum allowed rounds")
    evaluation: EvidenceEvaluationItem = Field(description="Final evidence evaluation")
    sources_queried: list[str] = Field(description="Names of knowledge sources queried")
    evidence_count: int = Field(description="Count of retrieved evidence items")
    answer: str | None = Field(default=None, description="Generated answer if sufficient")


class RetrievalTraceStepItem(BaseModel):
    """Single execution step item in an agentic retrieval trace."""

    step_index: int = Field(description="Step sequence index")
    step_type: str = Field(description="Step classification: plan, retrieve, evaluate, rewrite")
    query: str = Field(description="Active query processed at this step")
    sources_contacted: list[str] = Field(
        default_factory=list,
        description="Sources queried during this step",
    )
    documents_retrieved_count: int = Field(
        default=0,
        description="Count of documents returned",
    )
    decision: str = Field(description="Agent rationale or next action decision")
    duration_ms: float = Field(default=0.0, description="Execution time for step in milliseconds")


class AgenticRetrievalRequest(BaseModel):
    """Request to execute an autonomous agent-driven retrieval loop."""

    query: str = Field(
        min_length=1,
        description="User question to solve with agentic retrieval loop",
        examples=[
            "What are the latest maintenance requirements for the Boeing 777X flutter damper?"
        ],
    )
    max_iterations: int = Field(
        default=3,
        ge=1,
        le=10,
        description="Hard limit on maximum retrieval iterations",
    )
    max_tool_calls: int = Field(
        default=6,
        ge=1,
        le=20,
        description="Hard limit on cumulative source tool invocations",
    )
    max_retrieved_documents: int = Field(
        default=20,
        ge=1,
        le=100,
        description="Hard limit on accumulated document snippets",
    )
    timeout_seconds: float = Field(
        default=10.0,
        ge=1.0,
        le=60.0,
        description="Hard timeout in seconds",
    )


class AgenticRetrievalResponse(BaseModel):
    """Structured response from the agentic retrieval loop."""

    session_id: str = Field(description="Unique trace session identifier")
    query: str = Field(description="Original user query")
    answer: str = Field(description="Final grounded synthesized answer")
    is_sufficient: bool = Field(description="Whether retrieved evidence satisfied sufficiency")
    total_iterations: int = Field(description="Total retrieval iterations executed")
    total_tool_calls: int = Field(description="Total tool calls invoked")
    total_documents_retrieved: int = Field(description="Count of retrieved document passages")
    termination_reason: str = Field(description="Reason the loop concluded")
    duration_ms: float = Field(description="Total elapsed execution time in milliseconds")
    citations: list[CitationItem] = Field(
        default_factory=list,
        description="Grounded citations backing the answer",
    )
    steps: list[RetrievalTraceStepItem] = Field(
        default_factory=list,
        description="Detailed chronological execution trace steps",
    )


class ResearchSubquestionItem(BaseModel):
    """Structured subquestion item in a multi-step research plan."""

    id: str = Field(description="Unique subquestion identifier")
    index: int = Field(description="Sequential execution index")
    question: str = Field(description="Focused subquestion text")
    subquestion_type: str = Field(description="Subquestion purpose type")
    target_entities: list[str] = Field(default_factory=list, description="Target entities")
    expected_output_type: str = Field(description="Expected information format")
    suggested_sources: list[str] = Field(
        default_factory=list,
        description="Recommended retrieval destinations",
    )
    depends_on: list[str] = Field(
        default_factory=list,
        description="IDs of prerequisite subquestions",
    )


class CreateResearchPlanRequest(BaseModel):
    """Request to generate a multi-step research plan for a complex inquiry."""

    query: str = Field(
        min_length=1,
        description="Complex user inquiry to break down into a structured research plan",
        examples=[
            "Compare TSMC and Intel manufacturing strategies, identify their major "
            "technology challenges, and assess implications for the semiconductor industry."
        ],
    )


class CreateResearchPlanResponse(BaseModel):
    """Response containing the decomposed structured research plan."""

    plan_id: str = Field(description="Unique plan identifier")
    original_query: str = Field(description="Original complex user inquiry")
    overall_goal: str = Field(description="High-level synthesis objective")
    estimated_complexity: str = Field(description="Complexity classification")
    suggested_synthesis_strategy: str = Field(description="Synthesis approach")
    created_at: str = Field(description="Plan creation timestamp")
    subquestions: list[ResearchSubquestionItem] = Field(
        description="Ordered subquestions breakdown",
    )


class SubquestionResultItem(BaseModel):
    """Execution trace, evidence, and intermediate answer for a research subquestion."""

    subquestion_id: str = Field(description="Subquestion identifier")
    index: int = Field(description="Sequential index")
    query: str = Field(description="Executed subquestion text")
    sources: list[str] = Field(default_factory=list, description="Utilized sources")
    evidence: list[str] = Field(default_factory=list, description="Retrieved evidence snippets")
    citations: list[CitationItem] = Field(default_factory=list, description="Citations")
    sub_answer: str = Field(default="", description="Intermediate synthesized sub-answer")
    status: str = Field(description="Execution status")
    duration_ms: float = Field(description="Execution duration in milliseconds")
    error: str | None = Field(default=None, description="Error detail if failed")


class ExecuteResearchRequest(BaseModel):
    """Request to execute full multi-step research inquiry."""

    query: str = Field(
        min_length=1,
        description="Complex inquiry to research and synthesize",
        examples=[
            "Compare TSMC and Intel manufacturing strategies, identify their major "
            "technology challenges, and assess implications for the semiconductor industry."
        ],
    )
    top_k_per_source: int = Field(
        default=3,
        ge=1,
        le=20,
        description="Number of passages to retrieve per source for each subquestion",
    )
    mode: str = Field(
        default="parallel",
        description="Execution mode: 'parallel' (topological waves) or 'sequential'",
    )
    max_concurrency: int = Field(
        default=4,
        ge=1,
        le=16,
        description="Maximum concurrent subquestion tasks in parallel mode",
    )
    timeout_seconds: float = Field(
        default=5.0,
        ge=0.01,
        le=30.0,
        description="Per-subquestion execution timeout in seconds",
    )
    max_retries: int = Field(
        default=2,
        ge=0,
        le=5,
        description="Maximum retries for transient subquestion failures",
    )


class ExecuteResearchResponse(BaseModel):
    """Response containing complete multi-step research execution outcomes."""

    research_id: str = Field(description="Unique research execution identifier")
    original_query: str = Field(description="Original complex user inquiry")
    final_synthesis: str = Field(description="Holistic final synthesized report")
    status: str = Field(description="Overall research status (completed, partial, failed)")
    total_duration_ms: float = Field(description="Total execution time in milliseconds")
    total_citations: list[CitationItem] = Field(
        default_factory=list,
        description="Consolidated citations across all subquestions",
    )
    subquestion_results: list[SubquestionResultItem] = Field(
        default_factory=list,
        description="Sequential list of subquestion execution outcomes",
    )


class CriticIssueItem(BaseModel):
    """Defect identified by the Critic Agent."""

    issue_type: str = Field(description="Flaw classification")
    severity: str = Field(description="Severity (low, medium, high, critical)")
    claim_or_passage: str = Field(description="Flawed passage or claim")
    reason: str = Field(description="Why this is a flaw")
    suggested_fix: str = Field(description="How to resolve this defect")


class CriticEvaluationItem(BaseModel):
    """Complete critique evaluation report item."""

    is_acceptable: bool = Field(description="True if draft passes quality bar")
    critique_score: float = Field(description="Quality score 0.0 to 1.0")
    issues: list[CriticIssueItem] = Field(
        default_factory=list,
        description="Specific defects found",
    )
    feedback_summary: str = Field(description="High-level feedback")
    action_recommended: str = Field(description="Action recommendation")


class CritiqueAnswerRequest(BaseModel):
    """Request to critique a draft answer against evidence."""

    question: str = Field(min_length=1, description="Question asked")
    draft_answer: str = Field(min_length=1, description="Draft answer to critique")
    evidence: list[str] = Field(
        default_factory=list,
        description="Retrieved evidence passages",
    )


class CritiqueAnswerResponse(BaseModel):
    """Response containing Critic evaluation report."""

    is_acceptable: bool = Field(description="True if draft is acceptable")
    critique_score: float = Field(description="Score between 0.0 and 1.0")
    issues: list[CriticIssueItem] = Field(description="Issues detected")
    feedback_summary: str = Field(description="Summary feedback")
    action_recommended: str = Field(description="Recommended action")


class SelfCorrectionAttemptItem(BaseModel):
    """Telemetry item for a single self-correction iteration."""

    iteration: int = Field(description="Iteration index")
    draft_answer: str = Field(description="Draft evaluated")
    evaluation: CriticEvaluationItem = Field(description="Critic output")
    revised_answer: str | None = Field(default=None, description="Revised answer if generated")
    duration_ms: float = Field(description="Attempt duration in ms")


class SelfCorrectAnswerRequest(BaseModel):
    """Request to run iterative self-correction loop on a draft answer."""

    question: str = Field(min_length=1, description="User question")
    draft_answer: str = Field(min_length=1, description="Initial draft answer")
    evidence: list[str] = Field(
        default_factory=list,
        description="Ground truth evidence snippets",
    )
    max_corrections: int = Field(
        default=2,
        ge=1,
        le=5,
        description="Maximum allowed correction iterations",
    )


class SelfCorrectAnswerResponse(BaseModel):
    """Response containing self-correction loop results."""

    question: str = Field(description="User question")
    original_draft: str = Field(description="Initial draft")
    final_answer: str = Field(description="Corrected output")
    iterations: int = Field(description="Total iterations performed")
    max_iterations: int = Field(description="Configured max iterations")
    is_corrected: bool = Field(description="True if answer was altered")
    final_evaluation: CriticEvaluationItem = Field(description="Final evaluation")
    attempts: list[SelfCorrectionAttemptItem] = Field(
        default_factory=list,
        description="Trace of correction attempts",
    )
    total_duration_ms: float = Field(description="Total execution time in ms")


class FactualClaimItem(BaseModel):
    """Individual factual assertion evaluated against evidence."""

    claim_id: str = Field(description="Unique claim identifier")
    claim_text: str = Field(description="Claim proposition evaluated")
    evidence_text: str | None = Field(default=None, description="Relevant evidence snippet")
    source: str | None = Field(default=None, description="Source name")
    support_status: str = Field(
        description="Outcome: SUPPORTED, PARTIALLY_SUPPORTED, UNSUPPORTED, CONTRADICTED",
    )
    confidence: float = Field(description="Confidence score 0.0 to 1.0")
    citation_chunk_id: str | None = Field(default=None, description="Referenced chunk ID")
    reason: str = Field(description="Justification for status")


class VerifyAnswerRequest(BaseModel):
    """Request to verify an answer claim-by-claim against evidence."""

    question: str = Field(min_length=1, description="Question asked")
    answer: str = Field(min_length=1, description="Answer to verify")
    evidence: list[str] = Field(
        default_factory=list,
        description="Evidence snippets or documents to verify against",
    )


class VerifyAnswerResponse(BaseModel):
    """Response containing full claim-level verification and sanitized answer."""

    report_id: str = Field(description="Unique verification report identifier")
    question: str = Field(description="Question asked")
    original_answer: str = Field(description="Original unverified answer")
    verified_answer: str = Field(description="Sanitized verified answer")
    total_claims: int = Field(description="Total claims analyzed")
    claims: list[FactualClaimItem] = Field(description="Detailed claim verification results")
    supported_count: int = Field(description="Count of SUPPORTED claims")
    partially_supported_count: int = Field(description="Count of PARTIALLY_SUPPORTED claims")
    unsupported_count: int = Field(description="Count of UNSUPPORTED claims")
    contradicted_count: int = Field(description="Count of CONTRADICTED claims")
    verified_ratio: float = Field(description="Ratio of supported claims")
    is_verified: bool = Field(description="True if zero unsupported and zero contradicted")
    duration_ms: float = Field(description="Verification duration in milliseconds")


class AgenticResearchLoopRequest(BaseModel):
    """Request for executing the complete end-to-end agentic research loop."""

    question: str = Field(
        min_length=1,
        max_length=2000,
        description="Comprehensive research question or multi-part comparison",
        examples=[
            "Compare TSMC and Intel strategies and assess industry impact."
        ],
    )
    max_research_iterations: int = Field(
        default=2,
        ge=1,
        le=5,
        description="Maximum re-retrieval iterations when evidence is insufficient",
    )
    max_concurrency: int = Field(
        default=4,
        ge=1,
        le=10,
        description="Maximum concurrent research subquestions executed in parallel",
    )
    enable_self_correction: bool = Field(
        default=True,
        description="Whether to run the Critic Agent and bounded self-correction loop",
    )
    enable_verification: bool = Field(
        default=True,
        description="Whether to run claim-by-claim answer verification and sanitization",
    )
    timeout_seconds: float = Field(
        default=60.0,
        gt=0.0,
        le=300.0,
        description="Overall timeout for the complete research loop in seconds",
    )


class AgenticResearchLoopResponse(BaseModel):
    """Response containing complete execution trace and verified final research answer."""

    loop_id: str = Field(description="Unique loop execution ID")
    question: str = Field(description="Input research question")
    intent: str = Field(description="Detected query intent")
    is_complex: bool = Field(description="Whether question was decomposed into multi-step plan")
    subquestions: list[ResearchSubquestionItem] = Field(
        default_factory=list,
        description="Executed research subquestions",
    )
    subquestion_results: list[SubquestionResultItem] = Field(
        default_factory=list,
        description="Subquestion execution outcomes and evidence",
    )
    draft_answer: str = Field(description="Initial synthesized draft")
    final_answer: str = Field(description="Final verified and cited research response")
    citations: list[CitationItem] = Field(
        default_factory=list,
        description="Consolidated citations supporting the final answer",
    )
    is_verified: bool = Field(
        default=True,
        description="Whether the final answer passed claim verification",
    )
    verified_ratio: float = Field(
        default=1.0,
        description="Ratio of supported claims in final answer",
    )
    total_duration_ms: float = Field(description="Total loop execution time in milliseconds")
    status: str = Field(description="Overall execution status: completed, partial, or failed")


class ComponentHealthCheck(BaseModel):
    """Health check outcome for a specific internal subsystem."""

    status: str = Field(description="Component status: healthy, degraded, or unhealthy")
    details: str | dict[str, Any] = Field(
        default="Component operational",
        description="Diagnostic information or error detail",
    )


class ReadinessResponse(BaseModel):
    """Kubernetes-ready service readiness check schema."""

    status: str = Field(description="Overall readiness status: ready or not_ready")
    ready: bool = Field(description="Boolean indicator if service can accept traffic")
    checks: dict[str, ComponentHealthCheck] = Field(
        default_factory=dict,
        description="Subsystem health status checks",
    )
    version: str = Field(description="Application version")
    environment: str = Field(description="Deployment environment")


class LivenessResponse(BaseModel):
    """Kubernetes-ready service liveness check schema."""

    status: str = Field(default="alive", description="Liveness status indicator")
    live: bool = Field(default=True, description="Boolean indicator if process is running")
    uptime_seconds: float = Field(description="Total process uptime in seconds")
    version: str = Field(description="Application version")
    environment: str = Field(description="Deployment environment")















